//created on: 12/09/2017
package com.sample

declare Persona
	nombre: String @key
end

declare Dia
	diaSemana: int @key
end

declare Mes
	mes: int @key
end

declare siMes
	pers: Persona
	mes: Mes @key
end

declare siDia
	pers: Persona
	dia: Dia @key
end	

declare noMes
	pers: Persona
	mes: Mes @key
end

declare noDia
	pers: Persona
	dia: Dia @key
end

declare antesDe
	pers1: Persona
	pers2: Persona
end

declare JuntosMesDia
	mes: Mes
	dia: Dia 
end

declare antesDeVarios
	dia: Dia
	pers1: Persona
	pers2: Persona
end

rule "Carga hechos"
    then
    	//Insertar dias y meses
    	Dia lunes = new Dia(1);
    	insert(lunes);
    	
    	Dia miercoles = new Dia(2);
    	insert(miercoles);
    	
    	Dia viernes = new Dia(3);
    	insert(viernes);
    	
    	Dia sabado = new Dia(4);
    	insert(sabado);
    	
    	Dia domingo = new Dia(5);
    	insert(domingo);
    	
    	
    	Mes febrero = new Mes(1);
    	insert(febrero);
    	
    	//MARZO OCUPADO
    	Mes marzo = new Mes(2);
    	insert(marzo);
    	
    	Mes junio = new Mes(3);
    	insert(junio);
    	
    	Mes julio = new Mes(4);
    	insert(julio);
    	
    	Mes diciembre = new Mes(5);
    	insert(diciembre);
    	
    	Persona paola = new Persona("Paola");
    	insert(paola);
    	//Paola marzo pero no sábado
    	insert(new siMes(paola,marzo));
    	insert(new noDia(paola,sabado));
    	
    	Persona rosa = new Persona("Rosa");
    	insert(rosa);
    	insert(new noMes(rosa,marzo));
    	insert(new noDia(rosa,miercoles));
    	insert(new noDia(rosa,viernes));
    	insert(new noDia(rosa,sabado));
    	insert(new noDia(rosa,domingo));
    	
    	Persona bruno = new Persona("Bruno");
    	insert(bruno);
    	insert(new noMes(bruno,marzo));
    	insert(new noDia(bruno,viernes));
    	insert(new noDia(bruno,sabado));
    	insert(new noDia(bruno,domingo));
    	
    	//Mario y tabata nacieron un fin de semana
    	Persona mario = new Persona("Mario");
    	insert(mario);
    	insert(new noMes(mario,marzo));
    	insert(new noMes(mario,diciembre));
    	insert(new noDia(mario,lunes));
    	insert(new noDia(mario,miercoles));
    	insert(new noDia(mario,viernes));
    	
    	Persona tabata = new Persona("Tabata");
    	insert(new noMes(tabata,febrero));
    	insert(new noMes(tabata,marzo));
    	insert(new noMes(tabata,julio));
    	insert(new noDia(tabata,lunes));
    	insert(new noDia(tabata,miercoles));
    	insert(new noDia(tabata,viernes));
    	insert(new antesDe(tabata,bruno));
    	
    	//Amigo que nacio en junio nació en domingo
    	insert(new JuntosMesDia(junio,domingo));
    	
    	//Amigo en lunes nació antes de Bruno y Mario
    	insert(new antesDeVarios(lunes,bruno,mario));
    	insert(new antesDeVarios(lunes,mario,bruno));
    	System.out.println("ya está lo carga hechos");
end

rule "Tabata"    
    when
        $p1: Persona("Tabata";)
        $p2: Persona("Bruno";)
        $AD: antesDe(pers1==$p1,pers2==$p2)
        $mes1: Mes(5;)
        $mes2: Mes(3;)
        $d1: Dia(5;)
    then
        insert(new noMes($p1,$mes1));
        insert(new siMes($p1,$mes2));
        insert(new siDia($p1,$d1));
        
end

rule "Rosa"
	when
		$d1: Dia(1;)
		$m1: Mes(1;)
		$p1: Persona("Mario";)
		$p2: Persona("Bruno";)
		$p3: Persona("Rosa";)
		$no: antesDeVarios($d1,$p1,$p2;)
	then
		insert(new siMes($p3,$m1));
		insert(new siDia($p3,$d1));
end

rule "Dia Bruno, Paola y Mario"
	when
		$d1: Dia(1;)
		$d2: Dia(2;)
		$d3: Dia(3;)
		$d4: Dia(4;)
		$d5: Dia(5;)
		$p1: Persona("Bruno";)
		$p2: Persona("Paola";)
		$p3: Persona("Mario";)
		noDia($p1,$d3;)
		noDia($p1,$d4;)
		noDia($p2,$d4;)
	then
		insert(new siDia($p1,$d2));
		insert(new noDia($p2,$d2));
		insert(new siDia($p2,$d3));
		insert(new noDia($p3,$d2));
		insert(new noDia($p3,$d3));
		insert(new siDia($p3,$d4));
		System.out.println("ya está lo de bruno");
end